export const GET_CITIES = 'GET_CITIES';
export const CITIES_LOADING = 'CITIES_LOADING';

export const GET_ITINERARIES = 'GET_ITINERARIES';
export const ITINERARIES_LOADING = 'ITINERARIES_LOADING';

export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ACTIVITIES_LOADING = 'ACTIVITIES_LOADING';

export const SINGLE_CITY = 'SINGLE_CITY';

export const SINGLE_USER = 'SINGLE_USER';

export const GET_FAVORITES = 'GET_FAVORITES';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';

export const FAVORITE_COUNT = "FAVORITE_COUNT";
export const FAVORITE_INC = "FAVORITE_INC";
export const FAVORITE_DEC = "FAVORITE_DEC";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';